Feat: freeze account
dynamic-framework/dynamic-retail-product-detail-template pull request #27
Opened 2024-05-20 19:04 UTC by lnazarit

2024-05-29 19:51 UTC, abe-modyo requested changes

2024-05-29 19:51 UTC, abe-modyo commented on src/components/ActionsSelectorSlider.tsx
> +  const updateAccounts = (e: boolean) => {
evitamos abreviaturas, la idea es que el código sea autodescriptivo, y generalmente e se usa para errores :)

2024-05-29 19:51 UTC, abe-modyo commented on src/components/ActionsSelectorSlider.tsx
> +          onChange={(e) => updateAccounts(e)}
"e" por acá también

2024-05-29 19:51 UTC, abe-modyo commented on src/store/selectors.ts
> +  (widget) => widget.accounts.map((e) => ({ ...e, freeze: widget.accountsFreezed[e.id] })),
por aca lo de e también, e = account.

2024-05-29 19:51 UTC, abe-modyo commented on src/services/interface.ts
> +  freeze?: boolean
juraría que no necesitas e freeze acá porque lo tienes en el base

2024-05-29 19:51 UTC, abe-modyo commented on src/services/interface.ts
> +  freeze?: boolean
juraría que no necesitas e freeze acá porque lo tienes en el base

2024-05-29 19:51 UTC, abe-modyo commented on src/services/hooks/useAccountsEffect.ts
> +        const dataFreezed = data.reduce<Record<string, boolean>>(
no usamos ni acc ni e, tiene que ser autodescriptivo o nos tocará documentar :)

2024-05-29 19:51 UTC, abe-modyo commented on src/services/hooks/useAccountsEffect.ts
> +          {},
esta logica podría ser parte del slice que toma las cuentas, el setAccounts puede crear esto también, pero dentro del slice.

2024-06-03 21:10 UTC, abe-modyo approved these changes

2024-06-04 17:26 UTC, johannrp27 approved these changes

2024-06-04 20:44 UTC, merged