feat: card information
dynamic-framework/dynamic-retail-product-detail-template pull request #28
Opened 2024-05-24 18:46 UTC by lnazarit

Card information

2024-06-03 21:21 UTC, abe-modyo requested changes
hay detalles del estilo del primer PR :)

2024-06-03 21:21 UTC, abe-modyo commented on src/components/ActionsSelectorSlider.tsx
>  }: Props) {
el salto en los argumentos 🙏🏻, se que no es tu cambio, pero si puedes arreglarlo sería genial

2024-06-03 21:21 UTC, abe-modyo commented on src/components/CountDownState.tsx
> +}: CountDownStateProps) {
```suggestion
type Props = {
  value: number;
  text: string;
};

export default function CountDownState(
  {
    value,
    text = '',
  }: Props,
) {
```

2024-06-03 21:21 UTC, abe-modyo commented on src/components/loaders/CircularLoaderWithTimer.tsx
> +export default function CountdownCircleTimer(props: Props) {
destructoring acá de props

2024-06-03 21:21 UTC, abe-modyo commented on src/components/modals/ModalCardInformation.tsx
> +  const numberInfo = (cardNumber: string) => (
podría recibir directamente el account.accountNumber sin recibirlo por argumento, y memoizarlo o mejor moverlo a otro componente.

2024-06-03 21:21 UTC, abe-modyo commented on src/hooks/useCountDown.tsx
> +const useCountdown = (value: number) => {
```suggestion
export default function useContDown(value: number) {
```

2024-06-03 21:21 UTC, abe-modyo commented on src/hooks/useCountDown.tsx
> +export default useCountdown;
```suggestion
```

2024-06-03 21:21 UTC, abe-modyo commented on src/styles/loadingCircle.scss
> +.mask {
```suggestion

.mask {
```

2024-06-03 21:21 UTC, abe-modyo commented on src/styles/loadingCircle.scss
> +}
```suggestion
}

```

2024-06-03 21:21 UTC, abe-modyo commented on src/styles/loadingCircle.scss
> +@keyframes mask {
```suggestion

@keyframes mask {
```

2024-06-04 17:30 UTC, johannrp27 submitted a review, later dismissed

2024-06-04 17:30 UTC, johannrp27 commented on package.json
> +    "@dynamic-framework/ui-react": "^1.21.0",
Subir a la 1.25.0

2024-06-05 16:58 UTC, abe-modyo approved these changes

2024-06-05 17:11 UTC, johannrp27 approved these changes

2024-06-05 17:11 UTC, merged