feat: add additional cards button
dynamic-framework/dynamic-retail-product-detail-template pull request #40
Opened 2024-11-12 20:49 UTC by pipemeyer

https://modyohq.atlassian.net/jira/software/projects/MPD/boards/262?assignee=557058%3Aef828537-622a-46b3-8976-9e6e090d6795&selectedIssue=MPD-381

2024-11-13 19:57 UTC, efbarong commented on src/components/modals/ModalMoreActions.tsx
> +  const account = useAppSelector(getAccountSelected)!;
```suggestion
  const account = useAppSelector(getAccountSelected)!;
  
```

2024-11-13 19:57 UTC, efbarong commented on src/components/modals/ModalMoreActions.tsx
> +  const MORE_ACTIONS = [
Como queda dentro del componente seria entonces renombrar a `moreActions` y todo el array dentro de un `useMemo` por el account.id

2024-11-18 02:09 UTC, johannrp27 commented on src/components/modals/ModalMoreActions.tsx
> +  const MORE_ACTIONS = [
Sí, tambien son hartas acciones, podría ser un archivo aparte

2024-11-18 02:15 UTC, johannrp27 requested changes

2024-11-18 02:15 UTC, johannrp27 commented on src/locales/es.json
> +      "newVirtualCard": "Solicitar tarjeta virtual",
Todas las traducciones están en inglés menos estas 3 haha

2024-11-18 18:15 UTC, johannrp27 approved these changes

2024-11-18 21:03 UTC, efbarong submitted a review, later dismissed

2024-11-18 21:03 UTC, efbarong commented on src/components/modals/ModalMoreActions.tsx
> +import { DModal, useDPortalContext, DIcon } from '@dynamic-framework/ui-react';
Caen

```suggestion
import { 
  DModal, 
  useDPortalContext, 
  DIcon,
 } from '@dynamic-framework/ui-react';
```

2024-11-19 14:38 UTC, johannrp27 submitted a review, later dismissed

2024-11-19 14:47 UTC, efbarong commented on src/components/modals/ModalMoreActions.tsx
> +import { DModal, useDPortalContext, DIcon } from '@dynamic-framework/ui-react';
Esto no quedó solucionado. Falta el salto de linea de cada propiedad (como la sugerencia)

2024-11-19 14:54 UTC, efbarong approved these changes

2024-11-19 14:56 UTC, johannrp27 approved these changes

2024-11-19 14:57 UTC, efbarong approved these changes

2024-11-19 14:59 UTC, merged